version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: sentiment-backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: sentiment-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    environment:
      - VITE_BACKEND_URL=http://backend:5000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
