- name: DevOps Project Setup on EC2
  hosts: web
  become: true
  become_method: sudo
  become_user: root

  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install Docker and Docker Compose
      apt:
        name:
          - docker.io
          - docker-compose
        state: present

    - name: Ensure Docker is started and enabled
      service:
        name: docker
        state: started
        enabled: true

    - name: Stop running containers (if any)
      shell: docker-compose down || true
      args:
        chdir: /home/ubuntu/devops-ML-app

    - name: Remove all containers (running or stopped)
      shell: docker rm -f $(docker ps -aq) || true
      args:
        executable: /bin/bash
        

    - name: Delete all Docker images
      shell: docker rmi -f $(docker images -aq) || true
      args:
        executable: /bin/bash

    - name: Prune Docker system
      shell: docker system prune -af --volumes || true
      args:
        executable: /bin/bash    

    - name: Delete devops-ML-app directory if it exists
      file:
        path: /home/ubuntu/devops-ML-app
        state: absent

    - name: Clone your app repository
      git:
        repo: https://github.com/Avdhoot12/ML-Full-Stack-Basic.git
        dest: /home/ubuntu/devops-ML-app
        version: main

    - name: Get public IP of the EC2 instance
      uri:
        url: http://checkip.amazonaws.com
        return_content: yes
      register: public_ip

    - name: Update frontend .env file with backend IP
      copy:
        dest: /home/ubuntu/devops-ML-app/frontend/.env
        content: |
          VITE_API_BASE_URL=http://{{ public_ip.content | trim }}:5000
        

    - name: Rebuild Docker images
      command: docker-compose build
      args:
        chdir: /home/ubuntu/devops-ML-app

    # - name: Pull latest Docker images from Docker Hub
    #   command: docker-compose pull
    #   args:
    #     chdir: /home/ubuntu/devops-ML-app

    - name: Run the app with Docker Compose
      command: docker-compose up -d
      args:
        chdir: /home/ubuntu/devops-ML-app
