- name: Devops Project Setup on EC2
  hosts: web
  # hosts: local
  become: true
  become_method: sudo
  become_user: root
  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install Dependencies
      apt:
        name: ['docker.io', 'docker-compose']
        state: present

    - name: Ensure Docker is started
      service:
        name: docker
        state: started
        enabled: true

    - name: Clone your app repository
      git:
        repo: https://github.com/Avdhoot12/ML-Full-Stack-Basic.git
        dest: /home/ubuntu/devops-ML-app
        version: main

    - name: Get public IP of the EC2 instance
      uri:
        url: http://checkip.amazonaws.com
        return_content: yes
      register: public_ip

    - name: update fronntend .env file with backend ip
      copy:
        dest: /home/ubuntu/devops-ML-app/frontend/.env
        content: |
          VITE_API_BASE_URL=http://{{ public_ip.content | trim }}:5000

    - name: Run the app with docker compose
      command: docker-compose up -d
      args:
        chdir: /home/ubuntu/devops-ML-app